"""add_xp_fields

Revision ID: 2dc888ebce04
Revises: 43ddfaea3495
Create Date: 2025-12-08 16:10:50.050444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc888ebce04'
down_revision: Union[str, Sequence[str], None] = '43ddfaea3495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('cardholder', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('installment_n', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('installment_total', sa.Integer(), nullable=True))
    
    # Manually fixed for NOT NULL constraint with default
    op.add_column('transactions', sa.Column('source_type', sa.String(), nullable=True))
    op.execute("UPDATE transactions SET source_type = 'MANUAL' WHERE source_type IS NULL")
    op.alter_column('transactions', 'source_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'source_type')
    op.drop_column('transactions', 'installment_total')
    op.drop_column('transactions', 'installment_n')
    op.drop_column('transactions', 'cardholder')
    # ### end Alembic commands ###
