"""add_recurring_system

Revision ID: 7fd98f3a22c3
Revises: d17d40dd88b4
Create Date: 2025-12-08 18:12:10.008458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '7fd98f3a22c3'
down_revision: Union[str, Sequence[str], None] = 'd17d40dd88b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', postgresql.ENUM('INCOME', 'EXPENSE', name='transactiontype', create_type=False), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('category_legacy', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_transactions')
    # ### end Alembic commands ###
