"""add_transfer_type

Revision ID: bc7338237716
Revises: 7fd98f3a22c3
Create Date: 2025-12-08 18:52:23.146004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7338237716'
down_revision: Union[str, Sequence[str], None] = '7fd98f3a22c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE transactiontype ADD VALUE 'TRANSFER'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
