"""add_recurring_dates

Revision ID: c4987ce930fe
Revises: 9e3e24f4a6c1
Create Date: 2025-12-09 13:59:55.956116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4987ce930fe'
down_revision: Union[str, Sequence[str], None] = '9e3e24f4a6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_transactions', sa.Column('start_date', sa.Date(), server_default='2025-01-01', nullable=False))
    op.add_column('recurring_transactions', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recurring_transactions', 'end_date')
    op.drop_column('recurring_transactions', 'start_date')
    # ### end Alembic commands ###
