"""add_is_verified_flag

Revision ID: c60687a27896
Revises: f9dfdf14ef8d
Create Date: 2025-12-11 19:58:49.181693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c60687a27896'
down_revision: Union[str, Sequence[str], None] = 'f9dfdf14ef8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.execute("UPDATE transactions SET is_verified = false")
    op.alter_column('transactions', 'is_verified', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_verified')
    # ### end Alembic commands ###
