"""add_reference_date

Revision ID: d17d40dd88b4
Revises: 2dc888ebce04
Create Date: 2025-12-08 17:33:14.383071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17d40dd88b4'
down_revision: Union[str, Sequence[str], None] = '2dc888ebce04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('reference_date', sa.Date(), nullable=True))
    op.execute("UPDATE transactions SET reference_date = date")
    op.alter_column('transactions', 'reference_date', existing_type=sa.Date(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'reference_date')
    # ### end Alembic commands ###
