"""add_source_to_simulation

Revision ID: f9dfdf14ef8d
Revises: c4987ce930fe
Create Date: 2025-12-09 16:48:06.284663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9dfdf14ef8d'
down_revision: Union[str, Sequence[str], None] = 'c4987ce930fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recurring_transactions', sa.Column('source_type', sa.String(), server_default='XP_ACCOUNT', nullable=False))
    op.add_column('scenario_items', sa.Column('source_type', sa.String(), server_default='MANUAL', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenario_items', 'source_type')
    op.drop_column('recurring_transactions', 'source_type')
    # ### end Alembic commands ###
